const APIURL = "https://api.themoviedb.org/3/discover/movie?api_key=4bdff0b7b1503da2954be3244d740dfe";
const IMGPATH = "https://image.tmdb.org/t/p/w1280";
const SEARCHAPI =
    "https://api.themoviedb.org/3/search/movie?&api_key=4bdff0b7b1503da2954be3244d740dfe&query=";


const main = document.getElementById("content");
const form = document.getElementById("form");
const search = document.getElementById("search");

// initially get fav movies
getMovies(SEARCHAPI);

    async function getMovies(url) {
    const resp = await fetch(url);
    const respData = await resp.json();

    console.log(respData);

    showMovies(respData.results);
}

function showMovies(movies) {
    // clear main
    main.innerHTML = "";

    movies.forEach((movie) => {
        const { poster_path, title, vote_average, overview } = movie;

        const movieEl = document.createElement("div");
        movieEl.classList.add("movie");

        movieEl.innerHTML = `
            <img
                src="${IMGPATH + poster_path}"
                alt="${title}"
            />
            <div class="movie-info">
                <h3>${title}</h3>
                <span class="${getClassByRate(
                    vote_average
                )}">${vote_average}</span>
            </div>
            <div class="overview">
                <h3>Overview:</h3>
                ${overview}
            </div>
        `;

        main.appendChild(movieEl);
    });
}

function getClassByRate(vote) {
    if (vote >= 8) {
        return "green";
    } else if (vote >= 5) {
        return "orange";
    } else {
        return "red";
    }
}

form.addEventListener("submit", (e) => {
    e.preventDefault();

    const cars = ["10 Rillington Place",
"12 Years a Slave",
"2010 The Year We Make Contact",
"A Simple Favor",
"Abominable",
"Ace in the Hole",
"Ad Astra",
"Air Force One",
"Alien From The Deep",
"Aliens",
"Alien",
"Alita Battle Angel",
"All The Presidents Men",
"Alone in the dark",
"American Animals",
"American Made",
"Anaconda",
"Angel Has Fallen",
"Ant-Man And The Wasp",
"Apollo 11",
"April And The Extraordinary World",
"Aquaman",
"Attack Of The 50 Foot Woman",
"Avengers Endgame",
"Avengers Infinity War",
"Baby Driver",
"Back to the Future",
"Bad Boys II",
"Bad Boys",
"Barbarella",
"Bates Motel",
"Batman Hush",
"Batman Ninja",
"Batman The Movie",
"Batman Under The Red Hood",
"Beat the devil",
"Ben-Hur",
"Best In Show",
"Between Worlds",
"Beware! The Blob",
"Black Christmas",
"Black Panther",
"Black Christmas",
"BlacKkKlansman",
"Blade Runner 2049",
"Blade Runner Black Out 2022",
"Blade Runner",
"Blockers",
"Body Heat",
"Body Melt",
"Booksmart",
"Brightburn",
"Bringing Up Baby",
"Brotherhood Of The Wolf",
"Bullet to the Head",
"Bumblebee",
"Bunny Lake Is Missing",
"Can You Ever Forgive Me",
"Candyman",
"Captain Marvel",
"Cat People",
"Clear and Present Danger",
"Colossal",
"Colossus The Forbin Project",
"Command and Control",
"Crawl",
"Creature from the Black Lagoon",
"Crimes of the Future",
"Crucible of Terror",
"Dark Phoenix",
"Daryl",
"Deadlier Than the Male",
"Deadpool 2",
"Deadwood The Movie",
"Death Spa",
"Death Valley",
"Death Wish",
"deathstalker 2",
"Deathstalker III",
"Deathstalker IV Match of Titans",
"Deathstalker",
"Deep Red",
"Demolition Man",
"Demonic Toys",
"Detroit",
"Do The Right Thing",
"Doctor Butcher",
"Doctor Sleep",
"Dollman Vs. Demonic Toys",
"Dollman",
"Doomsday",
"Double Jeopardy",
"Dr. Goldfoot And The Bikini Machine",
"Dr. Phibes Rises Again",
"Dracula 2000",
"Drowning by Numbers",
"Dumbo",
"Dunkirk",
"Duplicates",
"Eighth Grade",
"Einsteins God Model",
"Elektra",
"Embrace of the Serpent",
"Erik the Viking",
"Ex Libris The New York Public Library",
"Eye of the Cat",
"Eyes of Laura Mars",
"Fail Safe",
"Fair Game",
"Fantastic Beasts The Crimes Of Grindelwald",
"Fast & Furious Presents Hobbs & Shaw",
"Faster Pussycat Kill Kill",
"Fatherland",
"Fear and Desire",
"Finding Nemo",
"Five",
"Force Majeure",
"Ford V Ferrari",
"Frankenstein Created Woman",
"Frankenstein",
"Free Fire",
"Free Solo",
"Frost Nixon",
"Ga, ga - Glory to the Heroes",
"Game Night",
"Geostorm",
"Get Out",
"Ghost in the Shell",
"Glass",
"Godzilla King Of The Monsters",
"Going Overboard",
"gold of the amazon women",
"Gold",
"Golem",
"Grace of Monaco",
"Grosse Pointe Blank",
"Guardians of the Galaxy Vol 2",
"GUNG HO",
"Halloween",
"Halloween",
"Hard Rain",
"Hell or High Water",
"Hells Angels on Wheels",
"Hereditary",
"High Life",
"Highlander",
"Hologram Man",
"Holy Hell",
"Homeward Bound",
"Honky Holocaust",
"Horrors of the Black Museum",
"House",
"Hunter Killer",
"I Tonya",
"Ice Age",
"Images",
"Imperium",
"In The Dust Of The Stars",
"Incarnate",
"Incredibles 2",
"Independence Day",
"Inferno",
"Insidious The Last Key",
"Isle of Dogs",
"It Chapter Two",
"It Comes at Night",
"It! The Terror from Beyond Space",
"IT",
"Jaws 2",
"Jaws 3",
"Jaws",
"John Wick Chapter 2",
"John Wick Chapter 3 - Parabellum",
"John Wick Chapter 3 Parabellum",
"Joker",
"Juan of the Dead",
"Judy",
"Jumanji Welcome to the Jungle",
"Jurassic World Fallen Kingdom",
"Killer Fish",
"King Of Thieves",
"Kiss the Girls",
"Knives Out",
"Lady Bird",
"Latitude Zero",
"Left Behind II Tribulation Force",
"Left Behind III World at War",
"Left Behind",
"Life",
"Logans Run",
"Logan",
"Mandy",
"Mars Attacks",
"Mary Queen of Scots",
"Masters of the Universe",
"Mean Girls",
"Mechanic Resurrection",
"Midsommar",
"Mile 22",
"Mindhorn",
"Mission Impossible - Fallout",
"Mission Impossible Rogue Nation",
"Mollys Game",
"Moonrise Kingdom",
"Mortal Engines",
"Murder by Death",
"My Friend Dahmer",
"Nail Gun Massacre",
"National Lampoons Christmas Vacation",
"National Lampoons European Vacation",
"National Lampoons Vacation",
"New Rose Hotel",
"Nocturama",
"Ocean's Eight",
"Oceans Eleven",
"Octaman",
"Once Upon A Time ... In Hollywood",
"One False Move",
"Osmosis Jones",
"Overboard",
"Overboard",
"Overlord",
"Pacific Heights",
"Pacific Rim Uprising",
"Panic in Year Zero",
"Paradise Lost The Child Murders at Robin Hood Hills",
"Parasite",
"Patty Hearst",
"Phenomena",
"Pinocchio",
"Polybius",
"Polytechnique",
"Pretty Maids All In A Row",
"Prometheus",
"Psych The Movie",
"Punisher War Zone",
"Quintet",
"Ralph Breaks The Internet",
"Rampage",
"Ran",
"Ratatouille",
"Raw",
"Ready or Not",
"Red Cliff II",
"Red Cliff",
"Red Riding- In the Year of Our Lord 1980",
"Remote Control",
"Renaissance",
"Reptilicus",
"Revenge of the Nerds",
"Robin Hood",
"Robin Hood",
"Royal Space Force ",
"Russian Ark",
"Safe",
"Satan's Triangle",
"Searching",
"Season Of The Witch",
"Seconds",
"Serenity",
"Set It Off",
"Shallow Grave",
"Shazam",
"Shoot 'Em Up",
"Siberia",
"Sicario Day of the Soldado",
"Skyjacked",
"Skyscraper",
"Slaughterhouse Five",
"Slumber Party Massacre 2",
"Smashing Time",
"Solaris",
"Solo A Star Wars Story",
"Sorry to Bother You",
"Spider-Man Far From Home",
"Spider-Man Into the Spider-Verse",
"Strange Invaders",
"Subway",
"Survival Zone",
"Suspiria",
"Swallows and Amazons",
"Sympathy For The Devil",
"Taking Tiger Mountain",
"Team America World Police",
"Teen Witch",
"Tequila Sunrise",
"Terminator 2 Judgment Day",
"Terror Eyes",
"The Age of Shadows",
"The Alphabet Murders",
"The AristoCats",
"The Asphyx",
"The Autopsy of Jane Doe",
"The Baader Meinhof Complex",
"The Bad News Bears",
"The Battery",
"The Beast Must Die ",
"The Black Cauldron",
"The Blackout",
"The Blue Iguana",
"The Boston Strangler",
"The Brain from Planet Arous",
"The Chain Reaction",
"The Color of Magic",
"The Commuter",
"The Conqueror",
"The Day Time Ended",
"The Deadly Invention",
"The Death of Stalin",
"The Deliberate Stranger - The Ted Bundy Story",
"The Doll Squad",
"The Enemy Below",
"The Equalizer 2",
"The Equalizer",
"The Exorcism of Emily Rose",
"The Fate of the Furious",
"The Final Programme",
"The Founder",
"The Game",
"The Golden Voyage Of Sinbad",
"The Good the Bad and the Ugly",
"The Green Hornet",
"The Green Slime",
"The Groundstar Conspiracy",
"The Handmaids Tale",
"The Hitcher",
"The House of the Devil",
"The Humanity Bureau",
"The Hurricane Heist",
"The Hurricane Heist",
"The Intruder Within",
"The Inventor Out for Blood in Silicon Valley",
"The Invisible Man",
"The Jungle Book",
"The Karate Kid",
"The Kentucky Fried Movie",
"The Lair Of The White Worm",
"The Last Battle",
"The Last Movie",
"The Lathe of Heaven",
"The Lego Batman The Movie",
"The Leopard",
"The Lift",
"The Lighthouse",
"The Long Kiss Goodnight",
"The Lost Boys",
"The Maltese Falcon",
"The Manchurian Candidate",
"The Mask",
"The Matrix",
"The Meg",
"The Million Game",
"The Nanny",
"The Night Walker",
"The Noah",
"The Nun",
"The Passion of Ayn Rand",
"The Platform",
"The Predator",
"The Red Turtle",
"The Resurrected",
"The Ritual",
"The Rookie",
"The Royal Tenenbaums",
"The Searchers",
"The Secret Life Of Pets 2",
"The Secret Life of Pets",
"The Serpent and the Rainbow",
"The Shape Of Water",
"The Siege at Ruby Ridge",
"The Sisters Brothers",
"The Slumber Party Massacre",
"The Space Children",
"The Spy Who Dumped Me",
"The Strange Woman",
"The Terminator",
"The Time Travelers",
"The Vanishing",
"The Vanishing",
"The Virgin Spring",
"The Void",
"The Wages Of Fear",
"The Wandering Earth",
"The War of the Robots",
"The War On Democracy",
"The Witches",
"The Panama Deception",
"They Shall Not Grow Old",
"Thirst",
"Thoroughbreds",
"Three Men And A Baby",
"Three Men and a Little Lady",
"To Catch A Killer",
"Tokyo Drifter",
"Tokyo Magnitude 8.0",
"Tomb Raider",
"Torso",
"Transformers The Last Knight",
"Two-Minute Warning",
"U.S. Marshals",
"Upgrade",
"Us",
"Vacation",
"Valley Girl ",
"Vegas Vacation",
"View from the Top",
"Village Of The Damned",
"Walk  Hard The Dewey Cox Story",
"Wall Street",
"War For The Planet Of The Apes",
"Weekend at Bernie's",
"Weird Science",
"Where the Sidewalk Ends",
"Which Way Is Up",
"Why Man Creates",
"Widows",
"Winchester",
"Wind River",
"Witness for the Prosecution",
"Wonder Woman Bloodlines",
"Wonder Woman",
"Wrecker",
"Yesterday",
"You Were Never Really Here",
"Zombies of the Stratosphere",
"Airliner Sky Battle",
"Birds Of Prey And The Fantabulous Emancipation Of One Harley Quinn",
"Blade II",
"Blade Trinity",
"Blade",
"Blue Sunshine",
"Boys State",
"Brahms The Boy II",
"Dead Heat",
"Despicable Me 2",
"Despicable Me 3",
"Despicable Me",
"Dune",
"Ernest & Celestine",
"Fanny And Alexander",
"Firewall",
"Gray Lady Down",
"Greenland",
"Hard Kill",
"I Killed Einstein, Gentlemen",
"In Fear",
"Irresistible",
"Jigsaw",
"Kidnap",
"King Arthur Legend Of The Sword",
"Kingsman The Golden Circle",
"Kiss The Girls And Make Them Die",
"Krull",
"Lady Macbeth",
"Logan Lucky",
"Mazes and Monsters",
"Meatballs",
"Moana",
"Moon Zero Two",
"Morning Patrol",
"Mother!",
"My Cousin Vinny",
"National Treasure",
"Netforce",
"Never Too Young To Die",
"Notorious",
"Palm Springs",
"Patrick",
"Presumed Innocent",
"Rogue",
"Rosencrantz and Guildenstern Are Undead",
"Selma",
"Shadow in the Cloud",
"She Dies Tomorrow",
"shock",
"Six Days Seven Nights",
"Some Girls Do",
"Song of the Sea",
"Sorcerer",
"Soul",
"Sputnik",
"Stalker",
"Star Trek Generations",
"Star Trek II The Wrath of Khan",
"Star Trek III The Search for Spock",
"Star Trek IV The Voyage Home",
"Star Trek V The Final Frontier",
"Star Trek VI The Undiscovered Country",
"Star Wars Episode IX - The Rise Of Skywalker",
"Stone ",
"Taffin",
"Tenet",
"The Astounding She Monster",
"The Atomic Submarine",
"The Autobiography of Nicolae Ceausescu",
"The Beast from 20,000 Fathoms",
"The Breaking Point",
"The Bride of Frankenstein",
"The Cassandra Crossing",
"The Clonus Horror",
"The Craft Legacy",
"The Damned",
"The Deep",
"The Devil Rides Out ",
"The Dungeonmaster",
"The Fountainhead",
"The Garbage Pail Kids Movie",
"The Hitcher_2007)",
"The Killers",
"The Legend of Drunken Master",
"The Mind Snatchers",
"The Most Dangerous Game",
"The Neanderthal Man",
"The Night Evelyn Came out of the Grave",
"The Panama Papers",
"The Runestone",
"The Spy Who Came in from the Cold",
"The Three Faces of Eve",
"They Call Me Jeeg",
"Thor Ragnarok",
"Three the Hard Way",
"Top Hat",
"Twisted Nerve",
"Unhinged",
"Valerie and her Week of Wonders",
"Vampires Los Muertos",
"Where Have All The People Gone",
"Winter Kills",
"Wolfwalkers",
"Wonder Woman 1984",
"Wonder Woman",
"Your Name",
"'71",
"10 Cloverfield Lane",
"100 Feet",
"12 Monkeys",
"12 to the Moon",
"1201",
"127 hours",
"13 Hours The Secret Soldiers of Benghazi",
"1",
"2 Fast 2 Furious",
"2 guns",
"2001-A Space Odyssey",
"2081",
"21 Jump Street",
"22 Jump Street",
"2Everything2Terrible2 Tokyo Drift",
"3 10 to yuma",
"3000 Miles To Graceland",
"300",
"41",
"4D Man",
"500 mph storm",
"5_Centimeters_Per_Second",
"8«",
"A Bay Of Blood",
"A Beautiful Mind",
"A Better Tomorrow",
"a boy and his dog",
"a bronx tale",
"A Bucket of Blood",
"A Field in England",
"A Fish Called Wanda",
"A Fistful Of Dollars",
"A Ghost Story",
"a girl walks home alone at night",
"A Lonely Place to Die",
"A Most Violent Year",
"A Scanner Darkly",
"A Serious Man",
"A Sound of Thunder",
"a study in terror",
"A Walk Among the Tombstones",
"A Zed And Two Noughts",
"Absolutely Fabulous The Movie",
"Accelerator",
"adventures in babysitting",
"Aerobicide",
"AFFLICTED",
"after earth",
"AGUIRRE, THE WRATH OF GOD",
"aint them bodies saints",
"Airplane 2",
"Airplane!",
"Akira",
"alan partridge alpha papa",
"Ali Fear Eats the Soul",
"Alien Covenant",
"Alien Resurrection",
"alien trespass",
"Alienator",
"Alphaville",
"Amazon Women on the Moon",
"America Imagine the World Without Her",
"American Hustle",
"American Movie",
"American Psycho",
"American Ultra",
"AmeriGeddon",
"An Act of War",
"an honest liar",
"Anatomy Of A Murder",
"And Then There Were None",
"android",
"Angel Heart",
"Angel's Egg",
"Annabelle Creation",
"Annabelle",
"Anonymous",
"Another Earth",
"Ant Man",
"Antibodies",
"Ants Panic at Lakewood Manor",
"Anvil! The Story of Anvil",
"Apex",
"ape",
"Apocalypse Now",
"apollo 18",
"arachnophobia",
"argo",
"Arise! SubGenius recruitment film #16",
"Armour of God II Operation Condor",
"Armour of God",
"army of darkness",
"Arn The Knight Templar",
"Arrival",
"arsenic and old lace",
"Art And Copy",
"As Above, So Below",
"Assassins Creed",
"Assault on Precinct 13",
"assault on wall street",
"Astro Boy",
"Astro Zombies",
"Atlantis The Lost Empire",
"Atlas Shrugged II - The Strike",
"Atlas Shrugged I",
"Atlas Shrugged Part III",
"Atomic Blonde",
"Attack of the Crab Monsters",
"Attack the Block",
"Audition",
"austin powers international man of mystery",
"Autopsy",
"Avengers Age of Ultron",
"Bad Boy Bubby",
"Bad Lieutenant",
"Barfly",
"batman & mr freeze subzero",
"Batman Returns",
"Batman The Dark Knight Returns Part 1",
"Batman The Dark Knight Returns Part 2",
"batman v superman",
"Batman",
"Battle Beyond the Sun",
"battle royale",
"Battleship Potemkin",
"beaches",
"Beetlejuice",
"behind the candelabra",
"below",
"ben",
"Beowulf",
"Beyond The Black Rainbow",
"Beyond the Valley of the Dolls",
"bicycle thieves",
"Big Bad Mama II",
"Big Bad Mama",
"Big Game",
"Big Trouble In Little China",
"birdemic 2",
"birdemic shock and terror",
"Birdman",
"black angel",
"Black Death",
"black dynamite",
"black hawk down",
"Black Mass",
"black moon",
"Black Narcissus",
"Black Scorpion",
"Black Sunday",
"Blacula",
"Blast Vegas",
"Blindness",
"Blood Beach",
"Blood Feast",
"Blood Freak",
"Bloodbath At The House Of Death",
"Bloodeaters",
"Bloodsport",
"Bloodstream",
"Bloody Moon",
"blow out",
"Blow-Up",
"Blown Away",
"Body Bags",
"Born American",
"boyz n the hood",
"Braindead",
"BRAINSCAN",
"Brainstorm",
"brave",
"brazil",
"breach",
"Breakdown",
"Breakout",
"Breeders",
"Bridesmaids",
"Bridge of Spies",
"broken city",
"Bronson",
"brooklyn's finest",
"Buffy the Vampire Slayer",
"buried alive",
"Buried",
"Butterfly Effect 3",
"C. H. U. D.",
"C.H.U.D. 2 - Bud the Chud",
"C.S.A. The Confederate States of America",
"Cabin Fever Patient Zero",
"cannibal girls",
"Cape Fear",
"Capote",
"Capricorn One",
"Captain America The First Avenger",
"Captain America The Winter Soldier",
"Captain America",
"captain phillips",
"Carnival of Souls",
"carnosaur",
"carrie",
"cat city",
"Cat Shit One",
"Cauldron of Blood",
"cellar dweller",
"Cemetery Man",
"Chappie",
"Charly",
"Chernobyl Diaries",
"Child 44",
"children of the corn",
"children shouldn't play with dead things",
"china o'brien 2",
"china o'brien",
"Chinatown",
"Chopping Mall",
"Citizen Kane",
"citizen x",
"Citizenfour",
"city of the dead",
"City On Fire",
"City Under the Sea",
"cleanskin",
"Cleopatra",
"Clerks 2",
"Cliffhanger",
"cloud atlas",
"Cobra",
"Coffy",
"Collision Course",
"Colpi di luce",
"come and see",
"Commando",
"Conan the Barbarian",
"Contagion",
"contamination",
"CONTROL ROOM",
"Cool Breeze",
"Coriolanus",
"Crash",
"creature",
"crime story",
"Crimson Peak",
"crimson tide",
"critters 2",
"critters 3",
"critters 4",
"critters",
"Cronos",
"cropsey",
"Cube Zero",
"Cult",
"Curse of the Black Widow",
"Curtains",
"Cyborg 2087",
"Cyborg 2",
"Cyborg Cop II",
"cyborg cop",
"Cyborg",
"Cyclone",
"Dancer In The Dark",
"dante's inferno",
"dante's inferno",
"Daredevil",
"dark angel",
"dark blue",
"Dark Ride",
"dark shade creek",
"dark skies",
"dark star",
"dark touch",
"Dark Waters",
"Das Boot",
"Das Experiment",
"Das Testament des Dr  Mabuse",
"Dawn of the Dead",
"Dawn of the Planet of the Apes",
"Day of Resurrection",
"Day of the Dead",
"Dazed and Confused",
"De Palma",
"dead fish",
"dead man down",
"Dead Mans Shoes",
"Dead Meat",
"dead mine",
"dead poets society",
"Dead Ringers",
"Deadly Friend",
"Deadpool",
"Death Bed The Bed That Eats",
"Death Machines",
"Death Machine",
"Death Of A President",
"Death Run",
"death ship",
"Death Weekend",
"Death Wish 2",
"Death Wish III",
"Death Wish IV",
"Death Wish V - Face of Death",
"Death Wish",
"Deathgasm",
"Deaths of Ian Stone",
"Deep Blue Sea",
"deep rising",
"deepstar six",
"Deepwater Horizon",
"DEF-CON 4",
"delta force 2",
"Dementia 13",
"Dementia",
"Demon City",
"Demon Seed",
"DEMON UNDER GLASS",
"Demonoid Messenger Of Death",
"Demons 2",
"Demons",
"Desire, the Vampire",
"Detour",
"devil dog hound of hell",
"devil express",
"devil hunter",
"devil times five",
"Diabolique",
"Dial M For Murder",
"die hard 2",
"Die Hard With A Vengeance",
"die hard",
"Die Welle",
"Digital Man",
"Dirty Pictures",
"district 9",
"django",
"doa dead or alive",
"Dobermann",
"Doctor Strange",
"Document of the Dead",
"dogma",
"dolls",
"dolly dearest",
"Don't Deliver Us From Evil",
"don't go in the house",
"Don't Go in the Woods",
"Don't Open 'Till Christmas",
"Don't Torture a Duckling",
"donato and daughter",
"Donnie Brasco",
"donnie darko",
"donovan's echo",
"Dont Breathe",
"DONT LOOK IN THE BASEMENT",
"Doomsday Machine",
"Doubt",
"down and dirty duck",
"downfall",
"dprk the land of whispers",
"Dr. Cyclops",
"Dragon Day",
"Dragon The Bruce Lee Story",
"Dragon Wasps",
"Dread",
"Dreamcatcher",
"DreamScape",
"Dressed to Kill",
"Drive Angry",
"drive in massacre",
"Drunken Master II",
"Dude Where's My Car",
"dungeons and dragons",
"earth dies screaming",
"easy rider",
"EAT AND RUN",
"Eating Raoul",
"Edge of Tomorrow",
"Electric Boogaloo The Wild Untold Story of Cannon Films",
"elvis",
"Embryo",
"Empire of Ash",
"end of watch",
"Ender's Game",
"ENDGAME",
"Enemy",
"Entourage",
"Equalizer 2000",
"Equilibrium",
"Equinox",
"Eraserhead",
"Escape from L.A.",
"Escape From New York",
"escape from tomorrow",
"EuroTrip",
"even money",
"EVERYTHING IS TERRIBLE! THE MOVIE",
"Evilspeak",
"Evolver",
"Ex Machina",
"Exam",
"Excision",
"Exit Humanity",
"Exit Through the Gift Shop",
"Experimenter",
"Exterminators Of The Year 3000",
"Eye of the Devil",
"Eyes Without A Face",
"F for Fake",
"Face Off",
"fade to black",
"Fahrenheit 451",
"Fail Safe",
"Fail-Safe",
"Fallen Angels",
"Family Plot",
"Fantastic Beasts and Where to Find Them",
"Fantastic Four",
"Fantastic Planet",
"Fantastic Four",
"Fast & Furious",
"fast and furious 6",
"Fast Five",
"Fast Times At Ridgemont High",
"faster pussycat! kill kill",
"fdr american badass",
"Feed",
"Fido",
"Fiend without a face",
"Final Girl",
"fire and ice",
"First Blood",
"First men in the moon",
"First men in the moon",
"First Spaceship On Venus",
"Fist of the North Star The Legend of Kenshiro",
"Fitzcarraldo",
"Flash Gordon",
"flesh eating mothers",
"Flesh for Frankenstein",
"FLESH FOR THE BEAST",
"FLETCH",
"Flight of Dragons",
"flight of the navigator",
"Following",
"foodfight",
"for the bible tells me so",
"for your height only",
"Forbidden Planet",
"Forbidden World",
"Forbidden Zone",
"Force Majeure_2014)",
"Foreign Correspondent",
"Forest Warrior",
"Fortress 2",
"fortress",
"Four Lions",
"Four Skulls of Jonathan Drake",
"Foxcatcher",
"foxy brown",
"fracture",
"Frankenstein Meets the Spacemonster",
"Frankenstein The True Story",
"Freakonomics",
"freakshow",
"Freaks",
"Freejack",
"Frenzy",
"Frequency",
"Friday",
"Fright Night 2",
"Fright Night Part 2",
"Fright Night",
"Fright Night",
"Frightmare",
"FROGS",
"From Beyond",
"From Paris With Love",
"From the earth to the moon",
"From Time to Time",
"From Within",
"Frontier",
"frozen",
"frozen",
"Furious 7",
"Futureworld",
"Galaxina",
"Galaxy Of Terror",
"Galaxy Quest",
"Game Change",
"gamer",
"Gamma People",
"GARGANTUA",
"Gas-s-s-s",
"Gaslight",
"Gator",
"Genocide",
"Ghost in the Shell - Innocence",
"Ghost in the Shell 2.0",
"Ghost in the Shell S.A.C. - Individual Eleven",
"Ghost in the Shell S.A.C. - Solid State Society",
"Ghost in the Shell S.A.C. - The Laughing Man",
"Ghostbusters",
"Ghostbusters",
"ghostwood",
"Ghoulies IV",
"GI Joe Retaliation",
"Ginger Snaps",
"Girl with a Pearl Earring",
"glen or glenda",
"go ask alice",
"God Told Me To",
"Gods Not Dead 2",
"Gods of Egypt",
"Godzilla vs. Destoroyah",
"godzilla vs. spacegodzilla",
"Godzilla",
"Gone Girl",
"Gone With The Wind",
"good will hunting",
"Goodbye Paradise",
"goodfellas",
"goon",
"gotti",
"grabbers",
"grave encounters",
"Grave Of The Fireflies",
"gravity",
"Green Lantern Extended Cut",
"Green Room",
"Green Street Hooligans",
"green zone",
"Gremlins",
"Grilled",
"groundhog day",
"Guardians of the Galaxy",
"Guardians",
"Guess Who's Coming To Dinner",
"guns girls and gambling",
"gyo",
"Hack-O-Lantern",
"Hacksaw Ridge",
"Halloween 2",
"Halloween 3 Season Of The Witch",
"Halloween 4 The Return Of Michael Myers",
"Halloween 5 The Revenge Of Michael Myers",
"Halloween 6 The Curse Of Michael Myers",
"Halloween H20",
"Halloween Resurrection",
"Hamlet 2",
"hangar 18",
"Harakiri",
"Harbinger Down",
"hard rock zombies",
"Hard Ticket to Hawaii",
"Harold and Kumar Go To White Castle",
"harry potter and the chamber of secrets",
"harry potter and the deathly hallows part 1",
"harry potter and the deathly hallows part 2",
"harry potter and the goblet of fire",
"harry potter and the half blood prince",
"harry potter and the order of the phoenix",
"harry potter and the prisoner of azkaban",
"harry potter and the sorcerers stone",
"Haunted",
"Haywire",
"He Knows You're Alone",
"He Never Died",
"he walked by night",
"Head",
"Hearts and Minds",
"Hearts of Darkness",
"Heat",
"heavy traffic",
"HELEN KELLER VS NIGHTWOLVES",
"Hell Night",
"hello mary lou prom night 2",
"helter skelter",
"helvetica",
"Henry portrait of a serial killer",
"Hidden Figures",
"Hidden",
"High Rise",
"high road to china",
"Hobgoblins",
"Hobsons Choice",
"Horrible Bosses",
"horror planet",
"Hospital Massacre",
"Hostel 2",
"Hostel",
"Hot Dog The Movie",
"Hot Shots Part Deux",
"Hot Shots",
"Hot Tub Time Machine 2",
"hot tub time machine",
"Hotel Rwanda",
"hotel transylvania",
"How to Train Your Dragon 2",
"How to Train Your Dragon",
"Howling II Your Sister Is a Werewolf",
"howling vi",
"howling v",
"howls moving castle",
"Hudson Hawk ",
"Human Desire",
"Humanoid Defender",
"humanoids from the deep",
"hunger",
"Hush",
"husk",
"H„xan",
"I Bury the Living",
"I Confess",
"I Drink Your Blood",
"I Married a Monster From Outer Space",
"i robot",
"I Saw the Devil",
"I Saw What You Did",
"I'm a cyborg but that's ok",
"Ice Cold In Alex",
"Idaho Transfer",
"identity",
"Idiocracy",
"idle hands",
"if....",
"Igby Goes Down",
"Il Decameron",
"ill manors",
"Ilsa She Wolf Of The SS",
"immortal",
"Impulse",
"in like flint",
"in the year of the pig",
"in time",
"incendies",
"incubus",
"Indestructible Man",
"Indiana Jones and the Last Crusade",
"Indiana Jones And The Temple Of Doom",
"Indiana Jones Raiders of the Lost Ark",
"Infernal Affairs",
"Inferno",
"Infestation",
"Inherent Vice",
"Inherit the Wind",
"Inhuman Resources",
"Ink",
"Inside Job",
"Inside Out",
"insidious chapter 2",
"Insidious",
"interface",
"International Airport",
"interstate 60",
"Interstellar",
"intrepidos punks",
"Intruder",
"Invaders From Mars",
"invasion of the animal people",
"Invasion of The Body Snatchers",
"Invasion USA",
"Invasion USA",
"Invitation to Hell",
"ip man the final fight",
"IP MAN",
"iron man 3",
"Iron Virgin Jun",
"island of terror",
"Island of the Burning Damned",
"Isolation",
"It Came from Hollywood",
"It Came From Outer Space",
"it conquered the world",
"It Follows",
"It the Terror from Beyond Space",
"Jack and Jill",
"Jack Reacher Never Go Back",
"jack reacher",
"Jacob's Ladder",
"Jagal - The Act of Killing",
"Jamaica Inn",
"Jason Bourne",
"jeepers creepers",
"Jem and the Holograms",
"Jodorowsky's Dune",
"John Carpenter's Vampires",
"John Wick",
"Johnny Mnemonic",
"Journey to the Far Side of the Sun",
"joy ride",
"joysticks",
"Judgment at Nuremberg",
"junk head",
"Jupiter Ascending",
"Jurassic World",
"Just Before Dawn",
"Justice League",
"Kafka",
"Kagaku ninja tai Gatchaman",
"Keanu",
"kick ass 2",
"Kickboxer",
"Kill List",
"Kill Me Three Times",
"Kill The Messenger",
"Kill Theory",
"killdozer",
"killer crocodile",
"killer elite",
"killing season",
"Killings at Outpost Zeta",
"Kindergarten Cop",
"king of new york",
"King of the Zombies",
"Kingsman The Secret Service",
"Kiss Kiss Bang Bang_2005)",
"Kiss me deadly",
"knight of the dead",
"Knightriders",
"Kong Skull Island",
"Kubo And The Two Strings",
"kuroi ame",
"L.A. Confidential",
"La Cueva de los Sue¤os Olvidados",
"La grande illusion",
"La Habitaci¢n de Fermat",
"La Nave de los Monstruos",
"LA VRIT",
"Labyrinth",
"lady frankenstein",
"Lady Terminator",
"Lake Dead",
"Lake mungo",
"Lars and the Real Girl",
"LASERBLAST",
"LAST_CANNIBAL_WORLD",
"lawrence of arabia",
"layer cake",
"leaves of grass",
"left behind",
"Legend of the Bog",
"Leon the Professional",
"let me in",
"Lethal Weapon 2",
"Lethal Weapon 3",
"Lethal Weapon 4",
"Lethal Weapon",
"Leviathan",
"life cycles",
"Life of Brian",
"Limitless",
"Lincoln",
"lion of the desert",
"LIQUID SKY",
"lisa and the devil",
"Lisa, Lisa",
"Little Nemo Adventures In Slumberland",
"live free or die hard",
"Locke",
"lockout",
"LONDON HAS FALLEN",
"Lone Survivor",
"lonelyhearts",
"Long Weekend",
"Looker",
"Looking Glass",
"lord of war",
"Los Cronocrimenes",
"Lost Highway",
"lucky number slevin",
"Lucy",
"Macabre",
"Macbeth",
"MacGruber",
"MacGyver Lost Treasure of Atlantis",
"MacGyver Trail to Doomsday",
"mad max 2 the road warrior",
"mad max beyond thunderdome",
"mad max",
"magic",
"mama",
"Man Bites Dog",
"Man Hunt",
"man of steel",
"man of tai chi",
"Man with a Movie Camera",
"Maniac Cop 2",
"Maniac Cop 3 Badge Of Silence",
"Maniac Cop",
"Mardi Gras Massacre",
"Mark‚ta Lazarov ",
"Marnie",
"Martin",
"Martyrs",
"Martyrs",
"Master of the Flying Guillotine",
"Max Headroom - 20 Minutes into the Future",
"MAXIMUM OVERDRIVE",
"meet the feebles",
"Meet the Hollowheads",
"meeting evil",
"Mega Shark VS Giant Octopus",
"MegaForce",
"memento",
"memoirs of a geisha",
"Memories of Murder",
"Metamorphosis",
"Meteor",
"metropia",
"metropolis",
"miami connection",
"Micro Men",
"Microwave Massacre",
"Midnight Special",
"Millers Crossing",
"Mindflesh",
"mindhunters",
"Mine",
"ministry of fear",
"Mirror Mirror",
"MirrorMask",
"misery",
"Missile to the Moon",
"Missing",
"Mission Stardust",
"Mississippi Grind",
"modern times",
"MODESTY BLAISE",
"Moneyball",
"Monster That Challenged The World",
"Monsters",
"Monstrosity",
"Monty Python and the Holy Grail",
"Moonchild",
"Moonstalker",
"moontrap",
"morons from outer space",
"Mortuary",
"Mr And Mrs Smith",
"Mr Nice",
"Ms 45",
"mud",
"Mulberry Street",
"Mulholland Drive",
"Mum & Dad",
"Murder On The Orient Express",
"Murders in the Rue Morgue",
"Mutant War",
"Mutator",
"Mutiny In Outer Space",
"My Darling Clementine",
"My Dinner With Andre",
"My Girl",
"My Mom's a Werewolf",
"My Name is Bruce",
"my stepmother is an alien",
"Mystery of The Wax Museum",
"Mnchhausen",
"Nausica„ of the Valley of the Wind",
"NEAR DARK",
"Necromancy ",
"needful things",
"Nemesis",
"neon genesis evangelion the end of evangelion",
"Neon Maniacs",
"night creatures",
"Night of the Creeps",
"Night of the Demon",
"Night of the Eagle",
"Night Of The Ghouls",
"Night Of The Lepus",
"night of the living dead",
"night of the living dead",
"Night Tide",
"Nightcrawler",
"Nightmare Man",
"Nightmare",
"No Blade Of Grass",
"no country for old men",
"No End in Sight",
"No Escape",
"Noah",
"Noam Chomsky Manufacturing Consent",
"Nocturnal Animals",
"Non-Stop",
"North By Northwest",
"Nosferatu the Vampyre",
"Not Of This Earth",
"Now You See Me 2",
"now you see me",
"Nurse Sherri",
"Oasis of the Zombies",
"oblivion",
"odd thomas",
"Of Unknown Origin",
"office space",
"ogre",
"olympus has fallen",
"Omega Cop",
"On the Beach",
"on the road",
"Once Bitten",
"Once Upon a Time in the West",
"one day in september",
"one, two, three",
"Operation Avalanche",
"Orgy Of The Dead",
"Ouija Origin of Evil",
"Ouija",
"Our Brand Is Crisis",
"Out of the Blue",
"out of the past",
"Outpost Black Sun 2012",
"Outpost",
"outrageous fortune",
"oz the great and powerful",
"Paddington",
"Pandorum",
"Pans Labyrinth",
"Pan",
"Paprika",
"Paradise Now",
"Paranormal Activity 2",
"Paranormal Activity 3",
"Paranormal Activity",
"parent trap",
"Paris, texas",
"parker",
"Passengers",
"Paths of Glory",
"Patriots Day",
"Paul",
"peeping tom",
"Penny Dreadful",
"Perfect Blue",
"Performance",
"Perkins 14",
"Persecuted",
"Persona",
"phantasm 2",
"phantasm 3",
"phantasm 4",
"phantasm",
"Philip K  Dick The Penultimate Truth",
"phobia",
"Picnic at Hanging Rock",
"Picture Mommy Dead",
"Pieces",
"piranha 3dd",
"Piranha Part Two The Spawning",
"Pi",
"Plaguers",
"plan 9 from outer space",
"Plan 9.1 from Outer Space",
"Planet of Dinosaurs",
"Planet Of The Vampires",
"Plankton",
"Play Misty for Me",
"Plunder Road",
"plymouth",
"Point Break",
"Police Story 3",
"Poltergeist 2",
"poltergeist",
"Poltergeist",
"Pompeii",
"POPaganda The Art & and Crimes of Ron English",
"Popstar Never Stop Never Stopping",
"porco rosso",
"possession",
"Postal",
"Predator 2",
"Predators",
"Predator",
"Predestination",
"Premium Rush",
"Primer",
"Prince of Darkness",
"prisoners of the lost universe",
"prisoners",
"privilege",
"Project Metalbeast",
"Project Nightmare",
"Prom Night",
"Prospero's Books",
"Psych-Out",
"Psycho Cop Returns",
"Psycho Cop",
"Psycho",
"pulp fiction",
"Pulse",
"Pumpkinhead",
"Puppet Master",
"puzzle",
"Q The Winged Serpent",
"Quatermass 2",
"Quatermass and the Pit",
"queen kong",
"Queen of Blood",
"Quicksilver",
"r i p d",
"R.O.T.O.R.",
"Rabid",
"radio free albemuth",
"Radioactive Dreams",
"Raising Arizona",
"Rapsodia Satanica",
"Rashomon",
"raven",
"Raw Deal",
"rawhead rex",
"re-animator",
"Real Genius",
"Rebecca",
"Red 2",
"Red Heat",
"Red Road",
"red scorpion",
"Red Sonja",
"red state",
"Red Sun",
"Reeds",
"Regular Show The Movie",
"reign of fire",
"remo williams the adventure begins",
"Repulsion",
"Reservoir Dogs",
"Resident Evil Afterlife",
"Resident Evil Apocalypse",
"resident evil degeneration",
"Resident Evil Extinction",
"resident evil retribution",
"Resident Evil The Final Chapter",
"Resident Evil",
"Restrepo",
"Retaliator",
"Revanche",
"Revenge Of The Red Baron",
"riddick",
"Rififi",
"riki oh the story of ricky",
"Rings",
"rinne",
"Rise of the Planet of the Apes",
"Rising Storm",
"rituals",
"River Of Death",
"Road House",
"Robo Vampire",
"Robocop",
"Robocop",
"Robocop",
"robot monster",
"rock & rule",
"rocketship xm",
"Rodan",
"Rogue One",
"Rollergator",
"Romper Stomper",
"Rope",
"Rosencrantz & Guildenstern Are Dead",
"Rubber",
"Run Silent Run Deep",
"Runaway",
"running scared",
"Ruthless People",
"Saboteur",
"Safe House",
"Safety Not Guaranteed",
"Safe",
"Salem's Lot",
"samsara",
"San Andreas Quake",
"san andreas",
"Santa Claus Conquers the Martians",
"Santa Claus",
"satan's school for girls",
"saturday the 14th",
"Saturn 3",
"Satyricon",
"saw 2",
"saw 3",
"saw 4",
"saw 5",
"saw 6",
"saw 7",
"saw",
"Scanners II The New Order",
"Scanners",
"Scarlet Street",
"Schizopolis",
"scott pilgrim vs the world",
"scream and scream again",
"Season of the Witch",
"senna",
"Separation",
"Sex And The City 2",
"Shadow Of A Doubt",
"shadow of the cat",
"Shane",
"Sharkman",
"shaun of the dead",
"Shaun The Sheep The Movie",
"She",
"Shin Gojira",
"Shivers",
"Shock Waves",
"Shocking Dark",
"Shogun Assassin",
"Shoot to Kill",
"shootfighter fight to the death",
"Shutter Island",
"Sicario",
"side effects",
"Sightseers",
"silent hill",
"SILENT NIGHT BLOODY NIGHT",
"silver bullet",
"Sin City A Dame to Kill For",
"Sin City",
"sinister",
"Skinned Deep",
"Skinner",
"skyfall",
"slacker",
"Slaughter",
"slave girls from beyond infinity",
"sleepaway camp",
"Slithis",
"Slugs",
"smiley",
"snake eater",
"snake eater 2",
"snake eater 3",
"Snake In The Eagles Shadow",
"Snakes On A Plane",
"Snatch",
"snitch",
"Snoop Dogg's hood of horror",
"Snow White And The Huntsman 2012",
"snowpiercer",
"Solaris ",
"Soldier",
"Something Evil",
"something weird",
"Sophie Scholl The Final Days",
"Source Code",
"Southern Comfort",
"Soylent Green",
"space battleship yamato",
"Space Camp",
"Space Mutiny",
"Space Raiders",
"Space Station 76",
"Spacehunter",
"Spasmo",
"special bulletin",
"Spectre",
"Spectre",
"speed zone",
"Speed 2 Cruise Control",
"Speed",
"Spellbound",
"spider baby",
"Splinter",
"SPLiT SECOND",
"spookies",
"Spotlight",
"Spy Game",
"Spy",
"SQUIRM",
"Stagecoach ",
"Stake Land",
"Stalker",
"Star Trek Beyond",
"Star Trek",
"Star Wars Episode I - The Phantom Menace",
"Star Wars Episode II - Attack of the Clones",
"Star Wars Episode III - Revenge of the Sith",
"Star Wars Episode VI - Return of the Jedi",
"Star Wars Episode V",
"Star Wars The Force Awakens",
"Star Wars",
"Starchaser",
"stargate",
"Starship Invasions",
"starship troopers",
"steel dawn",
"steel frontier",
"Steel",
"Stephen King's It",
"Stitches",
"stolen",
"Stone Cold",
"Stonehenge Apocalypse",
"storm of the century",
"storm of the century",
"Straight Outta Compton",
"Strange Days",
"Stranger From Venus",
"Strangers On A Train",
"Street Trash",
"Streetwise",
"Stryker",
"Student Bodies",
"Submarine",
"suddenly",
"Suddenly",
"Suffragette",
"Suicide Squad",
"Sukiyaki Western Django",
"Sully",
"summer wars",
"sunshine cleaning",
"Super",
"Super 8",
"Super Mario Bros.",
"superbad",
"supergirl",
"superman red son",
"Supermen Against The Orient",
"superstition",
"Survival of the Dead",
"Suspicion",
"Suspiria 1977",
"Swimming with Sharks",
"sword of the stranger",
"Synecdoche, New York",
"Taken 3",
"Taken",
"Tales from the Gimli Hospital",
"Tammy And The T-Rex",
"tangled",
"tanin no kao",
"Tarantula ",
"Targets",
"Taxi Driver",
"techno police 21c",
"ted",
"Teenage Exorcist",
"Teenage Mutant Ninja Turtles",
"TekWar",
"TekWar TekJustice",
"TekWar TekLab",
"TekWar TekLords",
"TELEFON",
"Tenebre",
"TERMINAL INVASION",
"Terminator 2 - Judgment Day",
"Terminator Genisys",
"terms and conditions may apply",
"Terror Squad",
"Terror Train",
"terrorvision",
"Testament",
"the 13th warrior",
"The 39 Steps ",
"The Abandoned",
"The Abominable Dr. Phibes",
"The Accountant",
"The Adventures of Baron Munchausen",
"the adventures of buckaroo banzai across the 8th dimension",
"The Adventures Of Stella Star_1978)",
"The Adventures of Tintin The Secret of the Unicorn",
"the alien dead",
"The Alien Factor",
"The alpha_incident",
"The Amazing Colossal Man",
"the amazing mr no legs",
"The Amazing Spider Man",
"The Amazing Transparent Man",
"The Ambassador",
"the andromeda strain",
"The Antichrist",
"The Ape",
"The Astral Factor",
"the atomic cafe",
"The Atomic Kid",
"the avengers",
"The Babadook",
"The Bad Seed ",
"the bad seed",
"the basketball diaries",
"The Battle Of Algiers",
"The Beast with a Million Eyes",
"the beastmaster",
"The Bees",
"The Big Boss",
"The Big Country",
"The Big Lebowski",
"The Big Short",
"The Birth of a Nation",
"the bling ring",
"The Blood on Satan's Claw",
"The Bone Collector",
"The Boogens",
"The Boondock Saints II All Saints Day",
"The Boondock Saints",
"The Boss",
"The Bothersome Man",
"the bourne identity",
"The Bourne Legacy",
"the boys from brazil",
"The Boy",
"the brain eaters",
"the brain that wouldn't die",
"the brain",
"The broken",
"The Brood",
"the bunker",
"the burning hell",
"the burning",
"the cabinet of dr. caligari",
"the call",
"The Cameraman",
"The Campaign",
"The Canterbury Tales",
"THE CANTERVILLE GHOST",
"The Cell",
"the changeling",
"The Chaser",
"the chinese ring",
"The Church",
"The City of the Lost Children",
"The Clone Returns Home",
"the colony",
"The Colossus of New York",
"the company you keep",
"The Conjuring 2",
"The Conjuring",
"The Crazies",
"The Creature Wasn't Nice ",
"the creeping flesh",
"The Cremators",
"the crow",
"the curse of the swamp creature",
"the cyclops",
"The da vinci treasure",
"the dark crystal",
"The Dark Half Stephen King",
"the dark hour",
"The Dark Knight",
"the day after",
"The Day It Came To Earth",
"The Day of the Beast",
"The Day the Earth Caught Fire",
"the day the earth stood still",
"THE DEAD ONE",
"The Deadly Spawn",
"the Deadly Tower",
"The Delta Force",
"The Departed",
"The Detective",
"The Devil Inside",
"the Devil's Hand",
"the devils rain",
"The Devils",
"The Dictator",
"the dirt bike kid",
"The Disaster Artist",
"the divide",
"The Dorm That Dripped Blood",
"The draughtsman's contract",
"the eagle",
"The Elite Squad",
"the emperors new groove",
"The End of August at the Hotel Ozone",
"the evictors",
"The Evil Dead",
"the evil dead",
"The Evil of Frankenstein",
"The Evil",
"The Ewok Adventure",
"The Expendables",
"the exterminating angel",
"The Faculty ",
"The Farthest_2017)",
"the fast and furious",
"The Fast and the Furious Tokyo Drift",
"The Final",
"the final countdown",
"The Final Terror",
"the flesh eaters",
"The Flower of Hawaii",
"THE FOOD OF THE GODS",
"the forbidden kingdom",
"the frozen ground",
"the galaxy invader",
"The Gates of Hell",
"The Gate",
"the ghoul",
"The Gift",
"The Girl on the Train",
"The Girl Who Leapt Through Time",
"The Girl with All the Gifts",
"The Giver",
"the gold rush",
"The Good, The Bad, The Weird",
"The Goonies",
"the gorgon",
"The Grapes of Death",
"The Gravedancers",
"The Graves",
"the great dictator",
"The Great Silence ",
"The Green Mile ",
"The Grey",
"The Grudge 2",
"The Guardian",
"The Guard",
"The Hallow",
"The Hamiltons",
"the hand that rocks the cradle",
"The Happening",
"The Hateful Eight",
"The Heat",
"the heist",
"The Help 2011 DVDRiP XviD AC3- MiSTERE",
"The Hidden",
"THE HILL",
"the hills have eyes",
"the hitch-hiker",
"The Hitchhiker's Guide to the Galaxy",
"the hobbit an unexpected journey",
"The Holy Mountain",
"The Horde 2009",
"The Horror at 37,000 Feet",
"the horror show",
"the host",
"The Hour Of The Wolf",
"The Hourglass Sanatorium",
"The House at the End of Time",
"The House By The Cemetery",
"The Human Centipede",
"The Hunger Games  Mockingjay - Part 2",
"the hunger games catching fire",
"The Hunger Games Mockingjay Part-1",
"The Hunger",
"the iceman",
"The Illusionist",
"The Immortals",
"the impossible",
"The Inbetweeners 2",
"The Inbetweeners Movie",
"The Incredible Melting Man",
"The Incredibly Strange Creatures",
"The Infiltrator",
"The Inglorious Bastards",
"The Initiation of Sarah",
"The Innocents ",
"The Interview",
"The Intruder",
"The Invisible Boy",
"The Jacket",
"the jar",
"The Killer Shrews",
"The Killer",
"The Killing",
"the lady vanishes",
"The Last Boy Scout",
"The Last Chase",
"The Last Days on Mars",
"the last detail",
"the last dinosaur",
"The Last House On The Left",
"The Last Man on Earth",
"The Last Picture Show",
"The Last Polka",
"the last stand",
"The Last Starfighter",
"The Legend Of Boggy Creek",
"the legend of the 7 golden vampires",
"the life and death of colonel blimp",
"The Lion Sleeps No More",
"The Little Girl Who Lives Down the Lane",
"The Little Shop of Horrors",
"The Living Dead at Manchester Morgue",
"The Lobster",
"The Lords of Magick",
"The Lost City of Z",
"the lost weekend",
"The Machine",
"The Mad Monster",
"the madness of king george",
"The Mafu Cage",
"the maltese falcon",
"The Man From Earth",
"The Man From U.N.C.L.E",
"The Man They Could Not Hang",
"The Man Who Shot Liberty Valance",
"The Man Who Wasn't There",
"the manster",
"the man",
"The Martian",
"The Master",
"The Mechanic",
"The Mechanic",
"The Medusa Touch",
"the miracle",
"The Mirror",
"THE MISSILES OF OCTOBER",
"The Monolith Monsters",
"the most dangerous game",
"The Mummy",
"The Murders in the Rue Morgue",
"The Mysterious Castle in the Carpathians",
"The Name Of The Rose",
"the navigator - a medieval odyssey",
"The Net",
"The Nice Guys",
"THE NIGHT FLIER",
"the night of the hunter",
"The Ninth Configuration",
"the ninth gate",
"The Number 23",
"the old dark house",
"the omen",
"The Other",
"the outsiders",
"The Ox Bow Incident ",
"The People Under the Stairs",
"The Phantom from 10,000 Leagues",
"the phantom planet",
"The Physician",
"The Pink Chiquitas",
"The Pit and the Pendulum",
"The Place Beyond the Pines",
"the place promised in our early days",
"the player",
"The Pleasure Garden",
"The Poughkeepsie Tapes",
"The President's Plane Is Missing",
"The Princess Bride",
"The Proposition ",
"The Psychotronic Man",
"The Punisher",
"the purge",
"The Pyramid",
"The Quatermass Xperiment",
"the quiet earth",
"The Quiet Family",
"the raid 2",
"The Razor's Edge",
"the recruit",
"the red balloon",
"the reincarnation of peter proud",
"The Return of The Six Million Dollar Man and The Bionic Woman",
"The Returned",
"the right stuff",
"the ring",
"The Ring Two",
"The Ripper",
"The Rite of Spring",
"the road",
"the robot vs the aztec mummy",
"The Room",
"The Rover",
"The Runner",
"the running man",
"The Sadist",
"The Scar Crow",
"the seasoning house",
"The Secret in Their Eyes",
"The Secret Invasion",
"the secret of nikola tesla",
"The Secret of NIMH",
"The Sentinel",
"the seventh seal",
"The Shock Doctrine",
"The Signal",
"The Silence of the Hams",
"the social network",
"The Spiral Staircase",
"The Stanford Prison Experiment",
"The Star Wars Holiday Special",
"The Stone Tape",
"the stoned age",
"The Stranger",
"The Swarm",
"the terminator",
"the terrornauts",
"the texas chainsaw massacre",
"The Thing from Another World",
"the thing with two heads",
"The Thing",
"The Thing",
"the third man",
"The Thirteenth Floor",
"the thousand eyes of dr mabuse",
"the time machine i found at a yardsale",
"the tomb of ligeia",
"The Toolbox Murders",
"The Town That Dreaded Sundown",
"The Treasure of Abbot Thomas",
"The Tripper",
"The Trip",
"The Twelve Tasks of Asterix",
"The Twilight Samurai",
"The Two Worlds of Jennie Logan",
"The Undertaker and His Pals",
"The Untouchables",
"The Vampire and the Ballerina",
"The Vanishing",
"The Vatican Tapes",
"The Vault Of Horror",
"The Vindicator",
"the visitor",
"The Walking Deceased",
"The War Lover",
"The War Room",
"the ward",
"The Warlords",
"the warriors",
"the watch",
"the wave",
"The Way Back",
"the way of the dragon",
"The Wind Rises",
"The Witch",
"The Wolf Man",
"The Wolf of Wall Street",
"the wolverine",
"the woman in black",
"The Worlds End",
"The Worst Witch",
"The X Files I Want to Believe",
"The Year of the Sex Olympics",
"the yesterday machine",
"The Young Offenders",
"The Bank Job",
"The Bed Sitting Room",
"The Believer 2001 DVDRip Xvid-Nile",
"The Birds 1963 DVDRip XviD-NoGRP",
"The Debt",
"The Driller Killer",
"The fearless vampire killers",
"The Fountain",
"The Man Who Knew Too Much 1956 DVDRip XviD-NoGRP",
"The Man With The Golden Arm 1955 PROPER DVDRip XviD-FiNaLe",
"The Muppets 2011",
"The Paradine Case",
"The Quest",
"The Raid Redemption 2011 720p HDRip DD5 1 Eng NL Subs",
"The Trouble With Harry",
"Theatre of Blood",
"Theodore Rex",
"Theres Something About Mary",
"THEY CAME FROM BEYOND SPACE",
"they nest",
"they saved hitler's brain",
"They Shoot Divas, Don't They",
"THEY_CAME_BACK",
"Thief",
"things to come",
"Thirteen Days",
"this is the end",
"This Island Earth",
"This Means War",
"thor the dark world",
"Thor",
"Thrashin",
"threads",
"Three Billboards Outside Ebbing Missouri",
"three cases of murder",
"THX 1138",
"Time Masters",
"Time Travelers",
"time walker",
"Time Warp",
"Timecop",
"Timeline ",
"Timequest",
"Timerider The Adventure Of Lyle Swann",
"Timeslip",
"titus",
"To Live and Die in LA",
"Tobor the Great",
"Tokyo Eyes",
"Tokyo Gore Police",
"Tokyo Story",
"Tomb Raider The Cradle Of Life",
"Tomb Raider",
"Tombs of the Blind Dead",
"Tomorrow I'll Wake Up and Scald Myself with Tea",
"Tooth & Nail",
"Topaz",
"Torn Curtain",
"Total recall",
"tough guys",
"Tourist Trap",
"Tower Heist",
"Tower",
"Tracks",
"Traffic",
"Trail of the screaming forehead",
"Train To Busan",
"trainspotting",
"Trainwreck",
"Traitor",
"trancers 2",
"trancers",
"Transcendence",
"Transformers Age of Extinction",
"transformers the movie",
"trapped",
"Tremors 2 - Aftershocks",
"Tremors 3",
"Tremors 4",
"Tremors",
"Triangle",
"trilogy of terror II",
"trilogy of terror",
"TrollHunter",
"true grit",
"true grit",
"True Lies",
"Tucker and Dale vs Evil",
"Turbo Kid",
"Turkey Shoot",
"TURKISH STAR WARS",
"Turtles Can Fly",
"Twelve",
"Twice Told Tales",
"twice upon a time",
"twin peaks fire walk with me",
"Twins of Evil",
"twisted",
"two lane blacktop",
"Two Mules for Sister Sara",
"Two Thousand Maniacs",
"unbreakable",
"Undefeatable",
"Under Capricorn",
"Under The Skin",
"underworld",
"Underworld  Awakening",
"underworld evolution",
"underworld rise of the lycans",
"Unearthed",
"Unforgiven ",
"Unknown",
"Unleashed",
"unlucky charms",
"Unrest",
"Unstoppable",
"Untraceable",
"Up 2009",
"Upstream Color",
"Urotsukidoji Legend of the Overfiend",
"used cars",
"vacancy",
"Valerian and the City of a Thousand Planets",
"valhalla rising",
"Valley of the Wolves Iraq",
"vampire circus",
"vampire's kiss",
"Vengeance of the Zombies",
"vertical limit",
"Vertigo",
"VHS ",
"Vicious Lips",
"Violent Years",
"Virtual Nightmare",
"VIRTUOSITY",
"visitors of the night",
"visitors",
"Viva Zapata",
"Voices",
"voyage to the planet of prehistoric women",
"voyage to the prehistoric planet",
"v_h_s_2",
"Wages Of Fear",
"waking life",
"Waltzes From Vienna",
"War Dogs",
"Warcraft",
"WarGames",
"Warlords of the 21st Century",
"Warning from Space",
"warp speed",
"Warriors of the Wasteland",
"Warrior",
"watchmen ultimate cut",
"watership down",
"way Of The Wicked",
"we own the night",
"Welcome to Me",
"Welt am Draht",
"Westworld",
"What About Bob",
"What Have You Done to Solange",
"What We Do In The Shadows",
"wheels of fire",
"when the wind blows",
"white house down",
"White Lightning",
"white zombie",
"WHO CAN KILL A CHILD",
"who",
"Wicked City",
"Wicked little things",
"willard",
"Winters Bone",
"Witchboard 2",
"Witchboard",
"Witchery",
"without a clue",
"Without Warning",
"Without Warning",
"without warning",
"WIZARDS",
"Wolf Children",
"woman in the dunes",
"Wonder Women",
"World Gone Wild",
"World of the Dead The Zombie Diaries",
"world's greatest dad",
"wreck-it ralph",
"Wristcutters A Love Story",
"wrongfully accused",
"W",
"X Men Days of Future Past",
"X The Unknown",
"X-Men 4 Origins Wolverine",
"Xtro",
"xXx Return of Xander Cage",
"Yakuza Apocalypse",
"zaat",
"zelig",
"zero dark thirty",
"Zero Days",
"Zero Effect",
"Zero to Sixty",
"ZIGEUNERWEISEN",
"Zodiac",
"Zombeavers",
"Zombi 3",
"Zombie 4",
"Zombie Bloodbath",
"zombie flesh eaters",
"Zombie Nightmare",
"Zombieland",
"Zombies of Mass Destruction",
"zomblies",
"Zone Troopers",
"zontar the thing from venus",
"Zoolander",
"zootopia",
"[REC]",
"2025 The World Enslaved By A Virus",
"A Kiss Before Dying",
"A League of Their Own",
"A Man for All Seasons",
"A Quiet Place Part II",
"About Endlessness",
"Accident Man",
"Adaptation",
"Another Round",
"Assassin 33 A D",
"Banana",
"Batman The Long Halloween Part One",
"Batman The Long Halloween Part 2",
"Binky Nelson Unpacified",
"Black Easter",
"Black Widow",
"Blast from the Past",
"Blow The Man Down",
"Broken Arrow",
"Broken Arrow",
"Candyman",
"Cars 2",
"Cars 3",
"Cars",
"Censor",
"Charley Varrick",
"Cleopatra Jones",
"Clifford The Big Red Dog",
"Cloudy with a Chance of Meatballs 2",
"Cloudy With A Chance Of Meatballs",
"Competition",
"Copshop",
"Cro Minion",
"Deep Blue Sea 2",
"Deep Blue Sea 3",
"Double Team",
"Dune",
"El Cid",
"Encanto",
"Enemies of the State",
"Eternals",
"Evangelion 3.0.1.01 Thrice Upon a Time",
"Eye Of The Beholder",
"Fallen",
"First Man",
"Flashback",
"Free Guy",
"From Hell It Came",
"G Men",
"Godzilla vs Kong",
"Gringo The Dangerous Life Of John McAfee",
"Gunga Din",
"Halloween Kills",
"Herbie Goes Bananas",
"High Crimes",
"Home Makeover",
"In Fabric",
"In the Earth",
"Into The Storm",
"Invasion From Inner Earth",
"Judas and the Black Messiah",
"Killing Them Softly",
"License To Drive",
"Limbo",
"Malignant",
"Menace II Society",
"Minion Scouts",
"Minions",
"Mower Minions",
"Murder By Numbers",
"My Man Godfrey",
"Naked Vengeance",
"Night and the City",
"Night of the Demon",
"Nine To Five",
"No Sudden Move",
"No Time To Die",
"No Way Out",
"Nobody",
"Orientation Day",
"Paddington 2",
"Paddington",
"Panic in the Mailroom",
"Peter Rabbit 2 The Runaway",
"Pig",
"Possessor",
"Promising Young Woman",
"Punishment Park",
"Puppy!",
"Ricochet",
"Riders of Justice",
"Rollercoaster",
"Romancing The Stone",
"Santa's Little Helpers",
"Sator",
"Scream",
"Sea Fever",
"sharks of the corn",
"Song of the South",
"Soul Man",
"Spencer",
"Spiral From the Book of Saw",
"Strange Behavior",
"Talk Radio",
"Tangled",
"The Amusement Park",
"The Blues Brothers",
"The Body Shop",
"The Card Counter",
"The Conjuring The Devil Made Me Do It",
"The Dark and the Wicked",
"The Dogs of War",
"The Giant Spider Invasion",
"The Great Alligator",
"The Green Knight",
"The Gruffalos Child",
"The Gruffalo",
"The Honeymoon Killers",
"The Ice Road",
"The Iron Giant",
"The Italian Job",
"The Italian Job",
"The Karate Kid Part 2",
"The Karate Kid Part III",
"The Lego Movie 2 The Second Part",
"The Lost Leonardo",
"The Man In The Gray Flannel Suit",
"The Mauritanian",
"The Million Eyes Of Sumuru",
"The Organization",
"The Secret Life of Kyle",
"The Seventh Day",
"The Suicide Squad",
"The Tomorrow War",
"The Tragedy of Macbeth",
"The Trial",
"The Unholy",
"The Wizard of Oz",
"The Wolf Of Snow Hollow",
"Those Who Wish Me Dead",
"Time Travelers",
"Tom Clancys Without Remorse",
"Totally Under Control",
"Training Wheels",
"Twisted",
"Underwater",
"Way Down",
"Weekend At Bernies II",
"Weiner",
"Went the Day Well",
"Wrath of Man",
"Wrong Turn 2 dead end",
"Wrong Turn 4 bloody beginnings",
"Wrong Turn 5 bloodlines",
"Wrong Turn 6 last resort",
"Wrong Turn",
"Wrong Turn",
"Wrong Turn_3 left for dead",
"Yellow is the New Black"];

    const random = Math.floor(Math.random() * cars.length);
    const oneofthecars = cars[random];
    console.log(oneofthecars);
    console.log(random, cars[random]);

    const searchTerm = "the thing";

    if (oneofthecars) {
        getMovies(SEARCHAPI + oneofthecars);

        search.value = "";
    }
});

window.onload = function(){
  // getMovies(SEARCHAPI);
  console.log("Rep");
}
